
modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="hitcolor"
version="1337"
displayName="HitColor"
logoFile=""
credits=""
authors="padiloi1337"
description=''''''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
